name: pull-request-security

on:
  pull_request:

permissions:
  actions: read
  security-events: write
  contents: read

jobs:
  dependencies-analysis:
    name: Dependencies Analysis (Differential)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Scan PR branch (after)
        uses: google/osv-scanner-action/osv-scanner-action@v1
        with:
          scan-args: "--format sarif --output pr_scan.sarif ./"
        continue-on-error: true

      - name: Checkout baseline commit
        run: git checkout ${{ github.event.pull_request.base.sha }}

      - name: Scan baseline branch (before)
        uses: google/osv-scanner-action/osv-scanner-action@v1
        with:
          scan-args: "--format sarif --output baseline_scan.sarif ./"
        continue-on-error: true

      - name: Compare analysis
        uses: google/osv-scanner-action/osv-reporter-action@v1
        with:
          old-analysis: baseline_scan.sarif
          new-analysis: pr_scan.sarif
          output: diff_report.sarif

      - name: Save differential report
        uses: actions/upload-artifact@v4
        with:
          name: dependencies-diff
          path: diff_report.sarif

  source-code-analysis:
    name: Source Code Analysis (Differential)
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: run differential analysis with semgrep
        run: |
          semgrep scan --config .semgrep --baseline-commit ${{ github.event.pull_request.base.sha }} --sarif --output semgrep_diff.sarif

      - name: Save differential report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-diff
          path: semgrep_diff.sarif
